services:
  brapi-nginx:
    image: nginx:stable
    restart: unless-stopped
    depends_on:
      - certbot
    volumes:
      - /home/jenkins/brapi.org/data/server-conf/certbot/conf:/etc/letsencrypt
      - /home/jenkins/brapi.org/data/server-conf/certbot/www:/var/www/certbot
      - /home/jenkins/brapi.org/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /home/jenkins/brapi.org/nginx/brapi-ssl.conf:/etc/nginx/sites-available/brapi-ssl.conf
    ports:
      - "80:80"
      - "443:443"
    networks:
      brapi_net:
        ipv4_address: 172.18.0.3
      test_server_net: {}
      jenkins_net: {}
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - /home/jenkins/brapi.org/data/server-conf/certbot/conf:/etc/letsencrypt
      - /home/jenkins/brapi.org/data/server-conf/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - brapi_net
networks:
    brapi_net:
        name: brapi_net
        driver: bridge
        ipam:
          config:
            - subnet: 172.18.0.0/16
              gateway: 172.18.0.1
    test_server_net:
        name: test_server_net
        driver: bridge
    jenkins_net:
        name: jenkins_net
        driver: bridge