services:
  jenkins:
    image: jenkins_python
    restart: unless-stopped
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  default:
    name: jenkins_net
    external: true